name: Email Verification
on: 
  push:
  workflow_dispatch: # Allows manual trigger

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 23f2004847@ds.study.iitm.ac.in
        run: echo "Verification step for IITM TDS""Hello, world from ${{ github.actor }}!"
